/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as JasaPembuatanWebsiteAplikasiLandingPageRouteImport } from './routes/jasa-pembuatan-website-aplikasi-landing-page'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPipelineRouteImport } from './routes/_authenticated/admin.pipeline'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminProposalsIndexRouteImport } from './routes/_authenticated/admin.proposals.index'
import { Route as AuthenticatedAdminLeadsIndexRouteImport } from './routes/_authenticated/admin.leads.index'
import { Route as ApiPublicTelegramTestRouteImport } from './routes/api/public/telegram/test'
import { Route as AuthenticatedAdminProposalsIdRouteImport } from './routes/_authenticated/admin.proposals.$id'
import { Route as AuthenticatedAdminLeadsIdRouteImport } from './routes/_authenticated/admin.leads.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const JasaPembuatanWebsiteAplikasiLandingPageRoute =
  JasaPembuatanWebsiteAplikasiLandingPageRouteImport.update({
    id: '/jasa-pembuatan-website-aplikasi-landing-page',
    path: '/jasa-pembuatan-website-aplikasi-landing-page',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPipelineRoute =
  AuthenticatedAdminPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProposalsIndexRoute =
  AuthenticatedAdminProposalsIndexRouteImport.update({
    id: '/proposals/',
    path: '/proposals/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsIndexRoute =
  AuthenticatedAdminLeadsIndexRouteImport.update({
    id: '/leads/',
    path: '/leads/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicTelegramTestRoute = ApiPublicTelegramTestRouteImport.update({
  id: '/api/public/telegram/test',
  path: '/api/public/telegram/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminProposalsIdRoute =
  AuthenticatedAdminProposalsIdRouteImport.update({
    id: '/proposals/$id',
    path: '/proposals/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsIdRoute =
  AuthenticatedAdminLeadsIdRouteImport.update({
    id: '/leads/$id',
    path: '/leads/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jasa-pembuatan-website-aplikasi-landing-page': typeof JasaPembuatanWebsiteAplikasiLandingPageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/leads/$id': typeof AuthenticatedAdminLeadsIdRoute
  '/admin/proposals/$id': typeof AuthenticatedAdminProposalsIdRoute
  '/api/public/telegram/test': typeof ApiPublicTelegramTestRoute
  '/admin/leads/': typeof AuthenticatedAdminLeadsIndexRoute
  '/admin/proposals/': typeof AuthenticatedAdminProposalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jasa-pembuatan-website-aplikasi-landing-page': typeof JasaPembuatanWebsiteAplikasiLandingPageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/leads/$id': typeof AuthenticatedAdminLeadsIdRoute
  '/admin/proposals/$id': typeof AuthenticatedAdminProposalsIdRoute
  '/api/public/telegram/test': typeof ApiPublicTelegramTestRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsIndexRoute
  '/admin/proposals': typeof AuthenticatedAdminProposalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/jasa-pembuatan-website-aplikasi-landing-page': typeof JasaPembuatanWebsiteAplikasiLandingPageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/leads/$id': typeof AuthenticatedAdminLeadsIdRoute
  '/_authenticated/admin/proposals/$id': typeof AuthenticatedAdminProposalsIdRoute
  '/api/public/telegram/test': typeof ApiPublicTelegramTestRoute
  '/_authenticated/admin/leads/': typeof AuthenticatedAdminLeadsIndexRoute
  '/_authenticated/admin/proposals/': typeof AuthenticatedAdminProposalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/jasa-pembuatan-website-aplikasi-landing-page'
    | '/sitemap.xml'
    | '/admin'
    | '/admin/analytics'
    | '/admin/pipeline'
    | '/admin/settings'
    | '/admin/'
    | '/admin/leads/$id'
    | '/admin/proposals/$id'
    | '/api/public/telegram/test'
    | '/admin/leads/'
    | '/admin/proposals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/jasa-pembuatan-website-aplikasi-landing-page'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/pipeline'
    | '/admin/settings'
    | '/admin'
    | '/admin/leads/$id'
    | '/admin/proposals/$id'
    | '/api/public/telegram/test'
    | '/admin/leads'
    | '/admin/proposals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/jasa-pembuatan-website-aplikasi-landing-page'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/pipeline'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/leads/$id'
    | '/_authenticated/admin/proposals/$id'
    | '/api/public/telegram/test'
    | '/_authenticated/admin/leads/'
    | '/_authenticated/admin/proposals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JasaPembuatanWebsiteAplikasiLandingPageRoute: typeof JasaPembuatanWebsiteAplikasiLandingPageRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicTelegramTestRoute: typeof ApiPublicTelegramTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jasa-pembuatan-website-aplikasi-landing-page': {
      id: '/jasa-pembuatan-website-aplikasi-landing-page'
      path: '/jasa-pembuatan-website-aplikasi-landing-page'
      fullPath: '/jasa-pembuatan-website-aplikasi-landing-page'
      preLoaderRoute: typeof JasaPembuatanWebsiteAplikasiLandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pipeline': {
      id: '/_authenticated/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AuthenticatedAdminPipelineRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/proposals/': {
      id: '/_authenticated/admin/proposals/'
      path: '/proposals'
      fullPath: '/admin/proposals/'
      preLoaderRoute: typeof AuthenticatedAdminProposalsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads/': {
      id: '/_authenticated/admin/leads/'
      path: '/leads'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AuthenticatedAdminLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/telegram/test': {
      id: '/api/public/telegram/test'
      path: '/api/public/telegram/test'
      fullPath: '/api/public/telegram/test'
      preLoaderRoute: typeof ApiPublicTelegramTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/proposals/$id': {
      id: '/_authenticated/admin/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/admin/proposals/$id'
      preLoaderRoute: typeof AuthenticatedAdminProposalsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads/$id': {
      id: '/_authenticated/admin/leads/$id'
      path: '/leads/$id'
      fullPath: '/admin/leads/$id'
      preLoaderRoute: typeof AuthenticatedAdminLeadsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminPipelineRoute: typeof AuthenticatedAdminPipelineRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminLeadsIdRoute: typeof AuthenticatedAdminLeadsIdRoute
  AuthenticatedAdminProposalsIdRoute: typeof AuthenticatedAdminProposalsIdRoute
  AuthenticatedAdminLeadsIndexRoute: typeof AuthenticatedAdminLeadsIndexRoute
  AuthenticatedAdminProposalsIndexRoute: typeof AuthenticatedAdminProposalsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminPipelineRoute: AuthenticatedAdminPipelineRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminLeadsIdRoute: AuthenticatedAdminLeadsIdRoute,
  AuthenticatedAdminProposalsIdRoute: AuthenticatedAdminProposalsIdRoute,
  AuthenticatedAdminLeadsIndexRoute: AuthenticatedAdminLeadsIndexRoute,
  AuthenticatedAdminProposalsIndexRoute: AuthenticatedAdminProposalsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JasaPembuatanWebsiteAplikasiLandingPageRoute:
    JasaPembuatanWebsiteAplikasiLandingPageRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicTelegramTestRoute: ApiPublicTelegramTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
